#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Translate remaining English msgstr to Chinese in zh.po"""

import re

zh_po = r"d:\BaiduNetdiskDownload\notifuse-main\console\src\i18n\locales\zh.po"

TRANSLATIONS = {
    '"{0}/{1}"': '"{0}/{1}"',
    '"CC"': '"抄送"',
    '"Choose when to publish \\"{0}\\"'"': '"选择发布时间 \\"{0}\\""',
    '"Contact has \\"active\\" subscription status"': '"联系人具有 \\"活跃\\" 订阅状态"',
    '"Do you want to send \\"{0}\\" immediately or schedule it for later?"': '"您想立即发送 \\"{0}\\" 还是稍后排程发送？"',
    '"e.g., My Anthropic Integration"': '"例如：我的 Anthropic 集成"',
    '"e.g., My Firecrawl Integration"': '"例如：我的 Firecrawl 集成"',
    '"e.g., My Supabase Integration"': '"例如：我的 Supabase 集成"',
    '"e.g., Product Updates"': '"例如：产品更新"',
    '"Each contact enters the automation only once"': '"每个联系人只能进入自动化一次"',
    '"edit"': '"编辑"',
    '"Edit {0} translation"': '"编辑 {0} 翻译"',
    '"Edit alt text"': '"编辑替代文本"',
    '"Edit Author"': '"编辑作者"',
    '"Edit broadcast"': '"编辑群发邮件"',
    '"Edit Content"': '"编辑内容"',
    '"Edit CSS"': '"编辑CSS"',
    '"Edit Custom Field Label"': '"编辑自定义字段标签"',
    '"Edit email template"': '"编辑邮件模板"',
    '"Edit Font Import"': '"编辑字体导入"',
    '"Edit HTML Content"': '"编辑HTML内容"',
    '"Edit Liquid Content"': '"编辑Liquid内容"',
    '"Edit notification"': '"编辑通知"',
    '"Edit Notification"': '"编辑通知"',
    '"Edit permissions"': '"编辑权限"',
    '"Edit Permissions for {0}"': '"为 {0} 编辑权限"',
    '"Edit Test Data"': '"编辑测试数据"',
    '"Edit Test Data (JSON)"': '"编辑测试数据(JSON)"',
    '"Edit Theme v{0}"': '"编辑主题 v{0}"',
    '"Edit value"': '"编辑值"',
    '"Editable markup"': '"可编辑标记"',
    '"Editor mode"': '"编辑器模式"',
    '"EHLO Hostname"': '"EHLO主机名"',
    '"Elapsed"': '"已用时间"',
    '"Element Padding"': '"元素内边距"',
    '"email"': '"邮件"',
    '"Email (Required)"': '"邮箱（必填）"',
    '"Email address is required for OAuth2"': '"OAuth2需要邮箱地址"',
    '"Email Attributes"': '"邮件属性"',
    '"Email Body Payload"': '"邮件正文负载"',
    '"Email bounced"': '"邮件退回"',
    '"Email field mapping is required"': '"需要邮箱字段映射"',
    '"Email mapping from previous session is invalid for this CSV. Please map fields manually."': '"上一次会话的邮箱映射对此CSV无效。请手动映射字段。"',
    '"Email mapping is missing or invalid"': '"邮箱映射缺失或无效"',
    '"Email mapping required"': '"需要邮箱映射"',
    '"Email Metrics"': '"邮件指标"',
    '"Email Only"': '"仅邮件"',
    '"Email Opens and Clicks Tracking"': '"邮件打开和点击追踪"',
    '"Email Options:"': '"邮件选项："',
    '"Email Preview"': '"邮件预览"',
    '"Email Provider Configuration Needed"': '"需要配置邮件提供商"',
    '"Email Provider Required"': '"需要邮件提供商"',
    '"Email Subject"': '"邮件主题"',
    '"Email subject ({0})"': '"邮件主题（{0}）"',
    '"Email Template"': '"邮件模板"',
    '"Email Title Settings"': '"邮件标题设置"',
    '"Email widths above 650px may not display correctly in some email clients"': '"宽度超过650px的邮件可能在某些邮件客户端中显示不正确"',
    '"Email:"': '"邮件："',
    '"Emoji Suggestions"': '"表情符号建议"',
    '"Empty column. Add text, button, or image content."': '"空列。添加文本、按钮或图片内容。"',
    '"Enable A/B Testing"': '"启用A/B测试"',
    '"Enable Anonymous Telemetry"': '"启用匿名遥测"',
    '"Enable closed captions by default"': '"默认启用隐藏式字幕"',
    '"Enable SMTP Bridge Server"': '"启用SMTP桥接服务器"',
    '"Enable the blog feature to publish articles and content on your custom domain homepage. Your blog will be accessible at"': '"启用博客功能以在您的自定义域名首页发布文章和内容。您的博客将可访问于"',
    '"Enable TLS encryption for SMTP connection"': '"为SMTP连接启用TLS加密"',
    '"Enable to fetch global data that will be available to all recipients in this broadcast. The data will be accessible in your templates using the \\"global_feed\\" variable."': '"启用以获取全局数据，该数据将对本群发邮件的所有收件人可用。数据可以在模板中使用 \\"global_feed\\" 变量访问。"',
    '"Enable to fetch personalized data for each recipient before sending their email. The data will be accessible in your templates using the \\"recipient_feed\\" variable."': '"启用以为每个收件人获取个性化数据。数据可以在模板中使用 \\"recipient_feed\\" 变量访问。"',
    '"Endpoint URL"': '"端点URL"',
    '"Enrolled"': '"已报名"',
    '"Enter {0}"': '"输入 {0}"',
    '"Enter a name for this block"': '"为此块输入名称"',
    '"Enter a name for this integration"': '"为此集成输入名称"',
    '"Enter a name for your workspace"': '"输入您的工作区名称"',
    '"Enter a unique alphanumeric ID"': '"输入唯一的字母数字ID"',
    '"Enter an email address to receive a test email:"': '"输入邮箱地址以接收测试邮件："',
    '"Enter author name"': '"输入作者名称"',
    '"Enter automation name"': '"输入自动化名称"',
    '"Enter avatar URL (optional)"': '"输入头像URL（可选）"',
    '"Enter background image URL"': '"输入背景图片URL"',
    '"Enter BCC email addresses"': '"输入密送邮箱地址"',
    '"Enter broadcast ID to confirm"': '"输入群发邮件ID以确认"',
    '"Enter button link URL or {{ url }}"': '"输入按钮链接URL或{{ url }}"',
    '"Enter button text..."': '"输入按钮文本..."',
    '"Enter CC email addresses"': '"输入抄送邮箱地址"',
    '"Enter CSS class name"': '"输入CSS类名"',
    '"Enter custom HTML code. When placed in mj-head, use for CSS styles, meta tags, or head elements. When placed in mj-body, use for body-level HTML structures, tracking pixels, or template logic."': '"输入自定义HTML代码。放在mj-head中时，用于CSS样式、元标签或头部元素。放在mj-body中时，用于正文级HTML结构、追踪像素或模板逻辑。"',
    '"Enter duration"': '"输入持续时间"',
    '"Enter email address"': '"输入邮箱地址"',
    '"Enter email title..."': '"输入邮件标题..."',
    '"Enter event names to filter"': '"输入要筛选的事件名称"',
    '"Enter file URL or use file manager"': '"输入文件URL或使用文件管理器"',
    '"Enter height"': '"输入高度"',
    '"Enter icon URL or select image"': '"输入图标URL或选择图片"',
    '"Enter image URL"': '"输入图片URL"',
    '"Enter image URL or select from storage"': '"输入图片URL或从存储中选择"',
    '"Enter JSON..."': '"输入JSON..."',
    '"Enter link URL or {{ url }}"': '"输入链接URL或{{ url }}"',
    '"Enter list description"': '"输入列表描述"',
    '"Enter list ID to confirm"': '"输入列表ID以确认"',
    '"Enter list name"': '"输入列表名称"',
    '"Enter logo URL or select image"': '"输入徽标URL或选择图片"',
    '"Enter number..."': '"输入数字..."',
    '"Enter or select a date"': '"输入或选择日期"',
    '"Enter or select a timezone"': '"输入或选择时区"',
    '"Enter path"': '"输入路径"',
    '"Enter preview text that appears in email clients..."': '"输入在邮件客户端中显示的预览文本..."',
    '"Enter recipient email address"': '"输入收件人邮箱地址"',
    '"Enter Reply-To email address"': '"输入回复地址邮箱"',
    '"Enter search term"': '"输入搜索词"',
    '"Enter select key or value"': '"输入选择键或值"',
    '"Enter slug..."': '"输入别名..."',
    '"Enter spacing"': '"输入间距"',
    '"Enter text, HTML or Liquid content..."': '"输入文本、HTML或Liquid内容..."',
    '"Enter the 6-digit code sent to {email}"': '"输入发送到 {email} 的6位数代码"',
    '"Enter the name of the custom event (e.g., \\'purchase\\', \\'signup\\')"': '"输入自定义事件的名称（例如 \\'purchase\\'、\\'signup\\'）"',
    '"Enter the API endpoint URL"': '"输入API端点URL"',
    '"Enter the API identifier"': '"输入API标识符"',
    '"Enter the API key"': '"输入API密钥"',
    '"Enter the API name"': '"输入API名称"',
    '"Enter the API secret"': '"输入API密钥"',
    '"Enter the API token"': '"输入API令牌"',
    '"Enter the AWS access key ID"': '"输入AWS访问密钥ID"',
    '"Enter the AWS region"': '"输入AWS区域"',
    '"Enter the AWS secret access key"': '"输入AWS密钥访问密钥"',
    '"Enter the bulk SMS ID"': '"输入批量短信ID"',
    '"Enter the channel ID"': '"输入渠道ID"',
    '"Enter the channel name"': '"输入渠道名称"',
    '"Enter the client ID"': '"输入客户端ID"',
    '"Enter the client secret"': '"输入客户端密钥"',
    '"Enter the configuration JSON"': '"输入配置JSON"',
    '"Enter the configuration value"': '"输入配置值"',
    '"Enter the consumer key"': '"输入消费者密钥"',
    '"Enter the consumer secret"': '"输入消费者密钥"',
    '"Enter the content"': '"输入内容"',
    '"Enter the custom endpoint URL"': '"输入自定义端点URL"',
    '"Enter the database host"': '"输入数据库主机"',
    '"Enter the database name"': '"输入数据库名称"',
    '"Enter the database password"': '"输入数据库密码"',
    '"Enter the database port"': '"输入数据库端口"',
    '"Enter the database URL"': '"输入数据库URL"',
    '"Enter the database username"': '"输入数据库用户名"',
    '"Enter the domain"': '"输入域名"',
    '"Enter the email"': '"输入邮箱"',
    '"Enter the email address"': '"输入邮箱地址"',
    '"Enter the endpoint"': '"输入端点"',
    '"Enter the endpoint URL"': '"输入端点URL"',
    '"Enter the environment"': '"输入环境"',
    '"Enter the environment variable name"': '"输入环境变量名"',
    '"Enter the environment variable value"': '"输入环境变量值"',
    '"Enter the event name"': '"输入事件名称"',
    '"Enter the file path"': '"输入文件路径"',
    '"Enter the filename"': '"输入文件名"',
    '"Enter the folder path"': '"输入文件夹路径"',
    '"Enter the font family"': '"输入字体系列"',
    '"Enter the footer text"': '"输入底部文本"',
    '"Enter the from address"': '"输入发件人地址"',
    '"Enter the from email"': '"输入发件人邮箱"',
    '"Enter the from name"': '"输入发件人名称"',
    '"Enter the function name"': '"输入函数名"',
    '"Enter the function URL"': '"输入函数URL"',
    '"Enter the header name"': '"输入头部名称"',
    '"Enter the header value"': '"输入头部值"',
    '"Enter the heading"': '"输入标题"',
    '"Enter the height in pixels"': '"输入高度（像素）"',
    '"Enter the home URL"': '"输入首页URL"',
    '"Enter the hostname"': '"输入主机名"',
    '"Enter the ID"': '"输入ID"',
    '"Enter the image URL"': '"输入图片URL"',
    '"Enter the input name"': '"输入输入名称"',
    '"Enter the integration name"': '"输入集成名称"',
    '"Enter the integration URL"': '"输入集成URL"',
    '"Enter the IP address"': '"输入IP地址"',
    '"Enter the JSON path"': '"输入JSON路径"',
    '"Enter the key"': '"输入密钥"',
    '"Enter the key ID"': '"输入密钥ID"',
    '"Enter the list ID"': '"输入列表ID"',
    '"Enter the list name"': '"输入列表名称"',
    '"Enter the location"': '"输入位置"',
    '"Enter the logo URL"': '"输入徽标URL"',
    '"Enter the message"': '"输入消息"',
    '"Enter the message ID"': '"输入消息ID"',
    '"Enter the metadata"': '"输入元数据"',
    '"Enter the method"': '"输入方法"',
    '"Enter the name"': '"输入名称"',
    '"Enter the namespace"': '"输入命名空间"',
    '"Enter the notification email"': '"输入通知邮箱"',
    '"Enter the number"': '"输入数字"',
    '"Enter the OAuth2 client ID"': '"输入OAuth2客户端ID"',
    '"Enter the OAuth2 client secret"': '"输入OAuth2客户端密钥"',
    '"Enter the object key"': '"输入对象密钥"',
    '"Enter the operation ID"': '"输入操作ID"',
    '"Enter the organization ID"': '"输入组织ID"',
    '"Enter the organization name"': '"输入组织名称"',
    '"Enter the origin URL"': '"输入来源URL"',
    '"Enter the output field name"': '"输入输出字段名"',
    '"Enter the page ID"': '"输入页面ID"',
    '"Enter the page title"': '"输入页面标题"',
    '"Enter the page URL"': '"输入页面URL"',
    '"Enter the password"': '"输入密码"',
    '"Enter the path"': '"输入路径"',
    '"Enter the port"': '"输入端口"',
    '"Enter the prefix"': '"输入前缀"',
    '"Enter the primary color"': '"输入主色"',
    '"Enter the private key"': '"输入私钥"',
    '"Enter the project ID"': '"输入项目ID"',
    '"Enter the public key"': '"输入公钥"',
    '"Enter the query"': '"输入查询"',
    '"Enter the query string"': '"输入查询字符串"',
    '"Enter the queue name"': '"输入队列名称"',
    '"Enter the reason"': '"输入原因"',
    '"Enter the recipient"': '"输入收件人"',
    '"Enter the redirect URL"': '"输入重定向URL"',
    '"Enter the region"': '"输入区域"',
    '"Enter the registry URL"': '"输入注册表URL"',
    '"Enter the reply-to address"': '"输入回复地址"',
    '"Enter the repository"': '"输入仓库"',
    '"Enter the repository URL"': '"输入仓库URL"',
    '"Enter the request body"': '"输入请求正文"',
    '"Enter the request headers"': '"输入请求头"',
    '"Enter the request method"': '"输入请求方法"',
    '"Enter the request URL"': '"输入请求URL"',
    '"Enter the response"': '"输入响应"',
    '"Enter the response body"': '"输入响应正文"',
    '"Enter the response headers"': '"输入响应头"',
    '"Enter the result"': '"输入结果"',
    '"Enter the retry count"': '"输入重试次数"',
    '"Enter the role"': '"输入角色"',
    '"Enter the route"': '"输入路由"',
    '"Enter the route path"': '"输入路由路径"',
    '"Enter the row ID"': '"输入行ID"',
    '"Enter the rule"': '"输入规则"',
    '"Enter the schema"': '"输入模式"',
    '"Enter the scope"': '"输入范围"',
    '"Enter the script"': '"输入脚本"',
    '"Enter the search query"': '"输入搜索查询"',
    '"Enter the search term"': '"输入搜索词"',
    '"Enter the secret"': '"输入密钥"',
    '"Enter the secret key"': '"输入密钥"',
    '"Enter the security token"': '"输入安全令牌"',
    '"Enter the segment ID"': '"输入细分ID"',
    '"Enter the segment name"': '"输入细分名称"',
    '"Enter the sender ID"': '"输入发件人ID"',
    '"Enter the sending domain"': '"输入发送域名"',
    '"Enter the server URL"': '"输入服务器URL"',
    '"Enter the service name"': '"输入服务名称"',
    '"Enter the session ID"': '"输入会话ID"',
    '"Enter the setting name"': '"输入设置名称"',
    '"Enter the setting value"': '"输入设置值"',
    '"Enter the size"': '"输入大小"',
    '"Enter the slug"': '"输入别名"',
    '"Enter the SMS ID"': '"输入短信ID"',
    '"Enter the source"': '"输入来源"',
    '"Enter the source URL"': '"输入源URL"',
    '"Enter the storage bucket"': '"输入存储桶"',
    '"Enter the storage region"': '"输入存储区域"',
    '"Enter the subject"': '"输入主题"',
    '"Enter the tag"': '"输入标签"',
    '"Enter the target URL"': '"输入目标URL"',
    '"Enter the template ID"': '"输入模板ID"',
    '"Enter the template name"': '"输入模板名称"',
    '"Enter the text"': '"输入文本"',
    '"Enter the time"': '"输入时间"',
    '"Enter the timeout"': '"输入超时"',
    '"Enter the timestamp"': '"输入时间戳"',
    '"Enter the timezone"': '"输入时区"',
    '"Enter the title"': '"输入标题"',
    '"Enter the token"': '"输入令牌"',
    '"Enter the topic"': '"输入主题"',
    '"Enter the topic name"': '"输入主题名称"',
    '"Enter the tracking ID"': '"输入追踪ID"',
    '"Enter the trigger"': '"输入触发器"',
    '"Enter the type"': '"输入类型"',
    '"Enter the unique ID"': '"输入唯一ID"',
    '"Enter the URL"': '"输入URL"',
    '"Enter the user ID"': '"输入用户ID"',
    '"Enter the username"': '"输入用户名"',
    '"Enter the value"': '"输入值"',
    '"Enter the variable name"': '"输入变量名"',
    '"Enter the version"': '"输入版本"',
    '"Enter the webhook ID"': '"输入Webhook ID"',
    '"Enter the webhook URL"': '"输入Webhook URL"',
    '"Enter the width in pixels"': '"输入宽度（像素）"',
    '"Enter the workspace ID"': '"输入工作区ID"',
    '"Enter the workspace name"': '"输入工作区名称"',
    '"Enter value"': '"输入值"',
    '"Enter width"': '"输入宽度"',
    '"Enter your API key"': '"输入您的API密钥"',
    '"Enter your API token"': '"输入您的API令牌"',
    '"Enter your database URL"': '"输入您的数据库URL"',
    '"Enter your email address"': '"输入您的邮箱地址"',
    '"Enter your endpoint URL"': '"输入您的端点URL"',
    '"Enter your password"': '"输入您的密码"',
    '"Enter your username"': '"输入您的用户名"',
    '"Enter your webhook URL"': '"输入您的Webhook URL"',
    '"Enter your website URL"': '"输入您的网站URL"',
    '"ended"': '"已结束"',
    '"Entity ID:"': '"实体ID："',
    '"Entries"': '"条目"',
    '"Entry"': '"条目"',
    '"Entry created"': '"条目已创建"',
    '"Entry deleted"': '"条目已删除"',
    '"Entry updated"': '"条目已更新"',
    '"Entries per page"': '"每页条目数"',
    '"Environment"': '"环境"',
    '"Environment Variables"': '"环境变量"',
    '"Error"': '"错误"',
    '"Error code"': '"错误代码"',
    '"Error details"': '"错误详情"',
    '"Error handling"': '"错误处理"',
    '"Error handling strategy"': '"错误处理策略"',
    '"Error loading preview"': '"加载预览出错"',
    '"Error loading template: Invalid template data"': '"加载模板出错：无效的模板数据"',
    '"Error message"': '"错误消息"',
    '"Error occurred"': '"发生错误"',
    '"Error on line {0}"': '"第 {0} 行出错"',
    '"Error parsing CSV: {0}"': '"CSV解析错误：{0}"',
    '"Error type"': '"错误类型"',
    '"Error: {0}"': '"错误：{0}"',
    '"Error: {errorMessage}"': '"错误：{errorMessage}"',
    '"Error:"': '"错误："',
    '"Errors"': '"错误"',
    '"Errors ({0} of {1} shown)"': '"错误（显示 {1} 中的 {0}）"',
    '"Event"': '"事件"',
    '"Event data"': '"事件数据"',
    '"Event name"': '"事件名称"',
    '"Event Names"': '"事件名称"',
    '"Event source"': '"事件来源"',
    '"Event time"': '"事件时间"',
    '"Event trigger"': '"事件触发器"',
    '"Event type"': '"事件类型"',
    '"Event Types"': '"事件类型"',
    '"Events"': '"事件"',
    '"Every {0}"': '"每 {0}"',
    '"Every time"': '"每次"',
    '"Example:"': '"示例："',
    '"except"': '"除...外"',
    '"Exception"': '"异常"',
    '"Expire after"': '"过期后"',
    '"Expired"': '"已过期"',
    '"Expiring soon"': '"即将过期"',
    '"Explicit"': '"显式"',
    '"excerpt"': '"摘要"',
    '"Excerpt"': '"摘要"',
    '"Exclude Unsubscribed"': '"排除退订者"',
    '"Exclude unsubscribed, bounced & complained recipients"': '"排除退订、退回和投诉的收件人"',
    '"exited"': '"已退出"',
    '"Expires:"': '"过期时间："',
    '"Export"': '"导出"',
    '"Export all"': '"导出全部"',
    '"Export Contacts to CSV"': '"导出联系人为CSV"',
    '"Export contacts"': '"导出联系人"',
    '"Export data"': '"导出数据"',
    '"Export HTML"': '"导出HTML"',
    '"Export settings"': '"导出设置"',
    '"Export subscribers"': '"导出订阅者"',
    '"Export to CSV"': '"导出为CSV"',
    '"Export to JSON"': '"导出为JSON"',
    '"Exporting all contacts"': '"导出所有联系人"',
    '"failed"': '"失败"',
    '"Failed"': '"失败"',
    '"Failed to accept invitation"': '"接受邀请失败"',
    '"Failed to activate automation"': '"激活自动化失败"',
    '"Failed to add to list: {error}"': '"添加到列表失败：{error}"',
    '"Failed to cancel broadcast"': '"取消群发邮件失败"',
    '"Failed to clear field"': '"清除字段失败"',
    '"Failed to compile template preview."': '"编译模板预览失败。"',
    '"Failed to complete setup"': '"完成设置失败"',
    '"Failed to configure"': '"配置失败"',
    '"Failed to connect"': '"连接失败"',
    '"Failed to copy to clipboard"': '"复制到剪贴板失败"',
    '"Failed to create"': '"创建失败"',
    '"Failed to create API key"': '"创建API密钥失败"',
    '"Failed to create automation: {0}"': '"创建自动化失败：{0}"',
    '"Failed to create broadcast: {0}"': '"创建群发邮件失败：{0}"',
    '"Failed to create category: {0}"': '"创建分类失败：{0}"',
    '"Failed to create contact"': '"创建联系人失败"',
    '"Failed to create folder:"': '"创建文件夹失败："',
    '"Failed to create integration"': '"创建集成失败"',
    '"Failed to create list"': '"创建列表失败"',
    '"Failed to create segment"': '"创建细分失败"',
    '"Failed to create sender"': '"创建发件人失败"',
    '"Failed to create template"': '"创建模板失败"',
    '"Failed to create user"': '"创建用户失败"',
    '"Failed to create webhook"': '"创建Webhook失败"',
    '"Failed to create workspace"': '"创建工作区失败"',
    '"Failed to delete"': '"删除失败"',
    '"Failed to delete API key"': '"删除API密钥失败"',
    '"Failed to delete automation"': '"删除自动化失败"',
    '"Failed to delete broadcast"': '"删除群发邮件失败"',
    '"Failed to delete contact"': '"删除联系人失败"',
    '"Failed to delete integration"': '"删除集成失败"',
    '"Failed to delete list"': '"删除列表失败"',
    '"Failed to delete segment"': '"删除细分失败"',
    '"Failed to delete sender"': '"删除发件人失败"',
    '"Failed to delete template"': '"删除模板失败"',
    '"Failed to delete user"': '"删除用户失败"',
    '"Failed to delete webhook"': '"删除Webhook失败"',
    '"Failed to delete workspace"': '"删除工作区失败"',
    '"Failed to disconnect"': '"断开连接失败"',
    '"Failed to fetch"': '"获取失败"',
    '"Failed to fetch contacts"': '"获取联系人失败"',
    '"Failed to fetch data"': '"获取数据失败"',
    '"Failed to fetch list"': '"获取列表失败"',
    '"Failed to fetch lists"': '"获取列表失败"',
    '"Failed to fetch segment"': '"获取细分失败"',
    '"Failed to fetch segments"': '"获取细分失败"',
    '"Failed to fetch sender"': '"获取发件人失败"',
    '"Failed to fetch settings"': '"获取设置失败"',
    '"Failed to fetch template"': '"获取模板失败"',
    '"Failed to fetch templates"': '"获取模板失败"',
    '"Failed to generate"': '"生成失败"',
    '"Failed to import"': '"导入失败"',
    '"Failed to import contacts"': '"导入联系人失败"',
    '"Failed to import data"': '"导入数据失败"',
    '"Failed to load"': '"加载失败"',
    '"Failed to load data"': '"加载数据失败"',
    '"Failed to load file"': '"加载文件失败"',
    '"Failed to login"': '"登录失败"',
    '"Failed to logout"': '"登出失败"',
    '"Failed to move"': '"移动失败"',
    '"Failed to process"': '"处理失败"',
    '"Failed to reconnect"': '"重新连接失败"',
    '"Failed to redirect"': '"重定向失败"',
    '"Failed to register"': '"注册失败"',
    '"Failed to remove"': '"移除失败"',
    '"Failed to remove item"': '"移除项目失败"',
    '"Failed to rename"': '"重命名失败"',
    '"Failed to resend"': '"重发失败"',
    '"Failed to reset"': '"重置失败"',
    '"Failed to restart"': '"重启失败"',
    '"Failed to resume"': '"恢复失败"',
    '"Failed to retry"': '"重试失败"',
    '"Failed to save"': '"保存失败"',
    '"Failed to save changes"': '"保存更改失败"',
    '"Failed to save settings"': '"保存设置失败"',
    '"Failed to send"': '"发送失败"',
    '"Failed to send broadcast"': '"发送群发邮件失败"',
    '"Failed to send email"': '"发送邮件失败"',
    '"Failed to send notification"': '"发送通知失败"',
    '"Failed to send test email"': '"发送测试邮件失败"',
    '"Failed to send test notification"': '"发送测试通知失败"',
    '"Failed to start"': '"启动失败"',
    '"Failed to start automation"': '"启动自动化失败"',
    '"Failed to start broadcast"': '"启动群发邮件失败"',
    '"Failed to stop"': '"停止失败"',
    '"Failed to stop automation"': '"停止自动化失败"',
    '"Failed to stop broadcast"': '"停止群发邮件失败"',
    '"Failed to subscribe"': '"订阅失败"',
    '"Failed to sync"': '"同步失败"',
    '"Failed to test"': '"测试失败"',
    '"Failed to test connection"': '"测试连接失败"',
    '"Failed to test webhook"': '"测试Webhook失败"',
    '"Failed to undo"': '"撤销失败"',
    '"Failed to unsubscribe"': '"退订失败"',
    '"Failed to update"': '"更新失败"',
    '"Failed to update API key"': '"更新API密钥失败"',
    '"Failed to update automation"': '"更新自动化失败"',
    '"Failed to update broadcast"': '"更新群发邮件失败"',
    '"Failed to update contact"': '"更新联系人失败"',
    '"Failed to update integration"': '"更新集成失败"',
    '"Failed to update list"': '"更新列表失败"',
    '"Failed to update profile"': '"更新配置文件失败"',
    '"Failed to update segment"': '"更新细分失败"',
    '"Failed to update sender"': '"更新发件人失败"',
    '"Failed to update settings"': '"更新设置失败"',
    '"Failed to update template"': '"更新模板失败"',
    '"Failed to update user"': '"更新用户失败"',
    '"Failed to update webhook"': '"更新Webhook失败"',
    '"Failed to update workspace"': '"更新工作区失败"',
    '"Failed to upload"': '"上传失败"',
    '"Failed to upload file"': '"上传文件失败"',
    '"Failure"': '"失败"',
    '"Failure reason"': '"失败原因"',
    '"False"': '"假"',
    '"Favorite"': '"收藏"',
    '"Feature"': '"功能"',
    '"Featured"': '"精选"',
    '"Features"': '"功能"',
    '"Field"': '"字段"',
    '"Field label"': '"字段标签"',
    '"Field mapping"': '"字段映射"',
    '"Field name"': '"字段名"',
    '"Field required"': '"字段必填"',
    '"Field type"': '"字段类型"',
    '"Field value"': '"字段值"',
    '"Fields"': '"字段"',
    '"File"': '"文件"',
    '"File already exists"': '"文件已存在"',
    '"File deleted"': '"文件已删除"',
    '"File description"': '"文件描述"',
    '"File is too large"': '"文件太大"',
    '"File manager"': '"文件管理器"',
    '"File name"': '"文件名"',
    '"File not found"': '"文件未找到"',
    '"File size"': '"文件大小"',
    '"File too large"': '"文件太大"',
    '"File type"': '"文件类型"',
    '"File type not supported"': '"文件类型不支持"',
    '"File URL"': '"文件URL"',
    '"Files"': '"文件"',
    '"Filter"': '"筛选"',
    '"Filter by"': '"按...筛选"',
    '"Filter by date"': '"按日期筛选"',
    '"Filter by event"': '"按事件筛选"',
    '"Filter by event name"': '"按事件名称筛选"',
    '"Filter by status"': '"按状态筛选"',
    '"Filter by type"': '"按类型筛选"',
    '"Filter contacts"': '"筛选联系人"',
    '"Filter events"': '"筛选事件"',
    '"Filter results"': '"筛选结果"',
    '"Filtered"': '"已筛选"',
    '"Filters"': '"筛选"',
    '"Find and Replace"': '"查找和替换"',
    '"Finished"': '"已完成"',
    '"First"': '"第一"',
    '"First name"': '"名"',
    '"First row contains headers"': '"第一行包含标题"',
    '"Fixed"': '"固定"',
    '"Flow"': '"流程"',
    '"Folder"': '"文件夹"',
    '"Folder name"': '"文件夹名称"',
    '"Folders"': '"文件夹"',
    '"Font"': '"字体"',
    '"Footer"': '"底部"',
    '"For"': '"用于"',
    '"Force"': '"强制"',
    '"Force delete"': '"强制删除"',
    '"Forgot password"': '"忘记密码"',
    '"Forgot your password?"': '"忘记密码？"' ,
    '"Form"': '"表单"',
    '"Format"': '"格式"',
    '"Format error"': '"格式错误"',
    '"From"': '"发件人"',
    '"From address"': '"发件人地址"',
    '"From email"': '"发件人邮箱"',
    '"From name"': '"发件人名称"',
    '"Full name"': '"全名"',
    '"Function"': '"函数"',
    '"Generate"': '"生成"',
    '"Generate API key"': '"生成API密钥"',
    '"Generate new password"': '"生成新密码"',
    '"Get"': '"获取"',
    '"Get data"': '"获取数据"',
    '"Get help"': '"获取帮助"',
    '"Get started"': '"开始使用"',
    '"Global"': '"全局"',
    '"Global data"': '"全局数据"',
    '"Global feed"': '"全局数据源"',
    '"Go"': '"转到"',
    '"Go back"': '"返回"',
    '"Go to"': '"转到"',
    '"Go to page"': '"转到页面"',
    '"Go to settings"': '"转到设置"',
    '"Greater than"': '"大于"',
    '"Greater than or equal"': '"大于或等于"',
    '"Group"': '"分组"',
    '"Group by"': '"分组依据"',
    '"Group contacts"': '"分组联系人"',
    '"Group name"': '"组名称"',
    '"Groups"': '"组"',
    '"Guard"': '"守护"',
    '"Handle"': '"处理"',
    '"Handler"': '"处理器"',
    '"Has"': '"有"',
    '"Has been"': '"已是"',
    '"Have"': '"有"',
    '"Header"': '"头部"',
    '"Headers"': '"头部"',
    '"Heading"': '"标题"',
    '"Height"': '"高度"',
    '"Height (px)"': '"高度（像素）"',
    '"Help"': '"帮助"',
    '"Help text"': '"帮助文本"',
    '"Hidden"': '"隐藏"',
    '"Hide"': '"隐藏"',
    '"Hide advanced settings"': '"隐藏高级设置"',
    '"High"': '"高"',
    '"History"': '"历史记录"',
    '"Home"': '"首页"',
    '"Hostname"': '"主机名"',
    '"Hour"': '"小时"',
    '"Hours"': '"小时"',
    '"Icon"': '"图标"',
    '"ID"': '"ID"',
    '"Identifier"': '"标识符"',
    '"Image"': '"图片"',
    '"Images"': '"图片"',
    '"Import"': '"导入"',
    '"Import contacts"': '"导入联系人"',
    '"Import CSV"': '"导入CSV"',
    '"Import data"': '"导入数据"',
    '"Import JSON"': '"导入JSON"',
    '"Importing contacts"': '"导入联系人中"',
    '"Inactive"': '"未激活"',
    '"Include"': '"包含"',
    '"Include all"': '"包含全部"',
    '"Include headers"': '"包含标题"',
    '"Included"': '"已包含"',
    '"Incorrect"': '"不正确"',
    '"Index"': '"索引"',
    '"Indicator"': '"指示器"',
    '"Info"': '"信息"',
    '"Insert"': '"插入"',
    '"Insert after"': '"在后面插入"',
    '"Insert before"': '"在前面插入"',
    '"Insert block"': '"插入块"',
    '"Insert column"': '"插入列"',
    '"Insert row"': '"插入行"',
    '"Insert text"': '"插入文本"',
    '"Inside"': '"内部"',
    '"Install"': '"安装"',
    '"Instance"': '"实例"',
    '"Integration"': '"集成"',
    '"Integrations"': '"集成"',
    '"Intensity"': '"强度"',
    '"Interface"': '"接口"',
    '"Internal"': '"内部"',
    '"Internal error"': '"内部错误"',
    '"Invalid"': '"无效"',
    '"Invalid API key"': '"无效的API密钥"',
    '"Invalid configuration"': '"无效的配置"',
    '"Invalid credentials"': '"无效的凭据"',
    '"Invalid data"': '"无效的数据"',
    '"Invalid email"': '"无效的邮箱"',
    '"Invalid email address"': '"无效的邮箱地址"',
    '"Invalid entry"': '"无效的条目"',
    '"Invalid file"': '"无效的文件"',
    '"Invalid file type"': '"无效的文件类型"',
    '"Invalid format"': '"无效的格式"',
    '"Invalid input"': '"无效的输入"',
    '"Invalid JSON"': '"无效的JSON"',
    '"Invalid key"': '"无效的密钥"',
    '"Invalid number"': '"无效的数字"',
    '"Invalid operation"': '"无效的操作"',
    '"Invalid parameter"': '"无效的参数"',
    '"Invalid parameters"': '"无效的参数"',
    '"Invalid password"': '"无效的密码"',
    '"Invalid permissions"': '"无效的权限"',
    '"Invalid request"': '"无效的请求"',
    '"Invalid response"': '"无效的响应"',
    '"Invalid schema"': '"无效的模式"',
    '"Invalid selection"': '"无效的选择"',
    '"Invalid signature"': '"无效的签名"',
    '"Invalid token"': '"无效的令牌"',
    '"Invalid type"': '"无效的类型"',
    '"Invalid URL"': '"无效的URL"',
    '"Invalid user"': '"无效的用户"',
    '"Invalid value"': '"无效的值"',
    '"Invitation"': '"邀请"',
    '"Invite"': '"邀请"',
    '"Invite members"': '"邀请成员"',
    '"Invite users"': '"邀请用户"',
    '"Invited"': '"已邀请"',
    '"Invited members"': '"已邀请成员"',
    '"IO error"': '"IO错误"',
    '"Is"': '"是"',
    '"Is active"': '"是否活跃"',
    '"Is admin"': '"是否管理员"',
    '"Is boolean"': '"是否为布尔值"',
    '"Is default"': '"是否为默认"',
    '"Is deleted"': '"是否删除"',
    '"Is disabled"': '"是否禁用"',
    '"Is enabled"': '"是否启用"',
    '"Is expired"': '"是否过期"',
    '"Is hidden"': '"是否隐藏"',
    '"Is invalid"': '"是否无效"',
    '"Is locked"': '"是否锁定"',
    '"Is pending"': '"是否待处理"',
    '"Is public"': '"是否公开"',
    '"Is required"': '"是否必填"',
    '"Is verified"': '"是否已验证"',
    '"Item"': '"项目"',
    '"Items"': '"项目"',
    '"JSON"': '"JSON"',
    '"JSON path"': '"JSON路径"',
    '"JSON schema"': '"JSON模式"',
    '"JSON value"': '"JSON值"',
    '"Key"': '"密钥"',
    '"Key ID"': '"密钥ID"',
    '"Key name"': '"密钥名"',
    '"Keys"': '"密钥"',
    '"Label"': '"标签"',
    '"Labels"': '"标签"',
    '"Language"': '"语言"',
    '"Last"': '"最后"',
    '"Last active"': '"最后活跃"',
    '"Last modified"': '"最后修改"',
    '"Last name"': '"姓"',
    '"Later"': '"稍后"',
    '"Layout"': '"布局"',
    '"Left"': '"左"',
    '"Left align"': '"左对齐"',
    '"Left margin"': '"左边距"',
    '"Length"': '"长度"',
    '"Less"': '"更少"',
    '"Level"': '"级别"',
    '"Library"': '"库"',
    '"Light"': '"浅色"',
    '"Limit"': '"限制"',
    '"Line"': '"行"',
    '"Line break"': '"换行"',
    '"Line height"': '"行高"',
    '"Line numbers"': '"行号"',
    '"Link"': '"链接"',
    '"Link copied to clipboard"': '"链接已复制到剪贴板"',
    '"Link URL"': '"链接URL"',
    '"Links"': '"链接"',
    '"List"': '"列表"',
    '"List ID"': '"列表ID"',
    '"List name"': '"列表名称"',
    '"List of"': '"列表"',
    '"List size"': '"列表大小"',
    '"Lists"': '"列表"',
    '"Load"': '"加载"',
    '"Load more"': '"加载更多"',
    '"Loading"': '"加载中"',
    '"Loading data"': '"加载数据中"',
    '"Local"': '"本地"',
    '"Location"': '"位置"',
    '"Lock"': '"锁定"',
    '"Log"': '"日志"',
    '"Log data"': '"日志数据"',
    '"Log entries"': '"日志条目"',
    '"Log level"': '"日志级别"',
    '"Log out"': '"登出"',
    '"Login"': '"登录"',
    '"Logout"': '"登出"',
    '"Logs"': '"日志"',
    '"Long"': '"长"',
    '"Long text"': '"长文本"',
    '"Look and feel"': '"外观"',
    '"Low"': '"低"',
    '"Mail"': '"邮件"',
    '"Mailchimp"': '"Mailchimp"',
    '"Main"': '"主要"',
    '"Manage"': '"管理"',
    '"Manage account"': '"管理账户"',
    '"Manage API keys"': '"管理API密钥"',
    '"Manage contacts"': '"管理联系人"',
    '"Manage integrations"': '"管理集成"',
    '"Manage lists"': '"管理列表"',
    '"Manage notifications"': '"管理通知"',
    '"Manage permissions"': '"管理权限"',
    '"Manage segments"': '"管理细分"',
    '"Manage senders"': '"管理发件人"',
    '"Manage templates"': '"管理模板"',
    '"Manage users"': '"管理用户"',
    '"Manage webhooks"': '"管理Webhook"',
    '"Manual"': '"手动"',
    '"Manual send"': '"手动发送"',
    '"Map"': '"映射"',
    '"Map fields"': '"映射字段"',
    '"Margin"': '"外边距"',
    '"Markdown"': '"Markdown"',
    '"Match"': '"匹配"',
    '"Match all"': '"匹配全部"',
    '"Match any"': '"匹配任意"',
    '"Match case"': '"区分大小写"',
    '"Max"': '"最大"',
    '"Max contacts"': '"最大联系人"',
    '"Max retries"': '"最大重试次数"',
    '"Max value"': '"最大值"',
    '"Maximum"': '"最大"',
    '"Maximum contacts"': '"最大联系人"',
    '"Maximum retries"': '"最大重试次数"',
    '"Maximum value"': '"最大值"',
    '"Media"': '"媒体"',
    '"Member"': '"成员"',
    '"Members"': '"成员"',
    '"Menu"': '"菜单"',
    '"Merge"': '"合并"',
    '"Merge fields"': '"合并字段"',
    '"Merge tag"': '"合并标签"',
    '"Message"': '"消息"',
    '"Message body"': '"消息正文"',
    '"Message ID"': '"消息ID"',
    '"Messages"': '"消息"',
    '"Metadata"': '"元数据"',
    '"Method"': '"方法"',
    '"Min"': '"最小"',
    '"Min contacts"': '"最小联系人"',
    '"Min retries"': '"最小重试次数"',
    '"Min value"': '"最小值"',
    '"Minimum"': '"最小"',
    '"Minimum contacts"': '"最小联系人"',
    '"Minutes"': '"分钟"',
    '"Mode"': '"模式"',
    '"Model"': '"模型"',
    '"Modified"': '"已修改"',
    '"Modify"': '"修改"',
    '"Module"': '"模块"',
    '"More"': '"更多"',
    '"More info"': '"更多信息"',
    '"More options"': '"更多选项"',
    '"Move"': '"移动"',
    '"Move down"': '"下移"',
    '"Move up"': '"上移"',
    '"Moved"': '"已移动"',
    '"My"': '"我的"',
    '"My account"': '"我的账户"',
    '"My integrations"': '"我的集成"',
    '"My profile"': '"我的配置文件"',
    '"My settings"': '"我的设置"',
    '"My workspace"': '"我的工作区"',
    '"Name"': '"名称"',
    '"Name field"': '"名称字段"',
    '"Name is required"': '"名称为必填"',
    '"Namespace"': '"命名空间"',
    '"Navigate"': '"导航"',
    '"Navigation"': '"导航"',
    '"Network error"': '"网络错误"',
    '"New"': '"新建"',
    '"New API key"': '"新建API密钥"',
    '"New application"': '"新建应用"',
    '"New automation"': '"新建自动化"',
    '"New broadcast"': '"新建群发邮件"',
    '"New campaign"': '"新建营销活动"',
    '"New channel"': '"新建渠道"',
    '"New contact"': '"新建联系人"',
    '"New custom field"': '"新建自定义字段"',
    '"New email"': '"新建邮件"',
    '"New entry"': '"新建条目"',
    '"New event"': '"新建事件"',
    '"New field"': '"新建字段"',
    '"New file"': '"新建文件"',
    '"New filter"': '"新建筛选"',
    '"New folder"': '"新建文件夹"',
    '"New form"': '"新建表单"',
    '"New group"': '"新建分组"',
    '"New integration"': '"新建集成"',
    '"New item"': '"新建项目"',
    '"New key"': '"新建密钥"',
    '"New label"': '"新建标签"',
    '"New list"': '"新建列表"',
    '"New member"': '"新成员"',
    '"New message"': '"新建消息"',
    '"New notification"': '"新建通知"',
    '"New password"': '"新密码"',
    '"New permission"': '"新建权限"',
    '"New post"': '"新建文章"',
    '"New query"': '"新建查询"',
    '"New report"': '"新建报告"',
    '"New role"': '"新建角色"',
    '"New rule"': '"新建规则"',
    '"New schedule"': '"新建排程"',
    '"New segment"': '"新建细分"',
    '"New sender"': '"新建发件人"',
    '"New sequence"': '"新建序列"',
    '"New settings"': '"新建设置"',
    '"New tag"': '"新建标签"',
    '"New task"': '"新建任务"',
    '"New template"': '"新建模板"',
    '"New user"': '"新建用户"',
    '"New value"': '"新值"',
    '"New version"': '"新版本"',
    '"New webhook"': '"新建Webhook"',
    '"New window"': '"新窗口"',
    '"New workspace"': '"新建工作区"',
    '"Newsletter"': '"通讯"',
    '"Next"': '"下一步"',
    '"Next step"': '"下一步"',
    '"Next version"': '"下一版本"',
    '"No"': '"否"',
    '"No access"': '"无访问权限"',
    '"No account"': '"无账户"',
    '"No activity"': '"无活动"',
    '"No API keys"': '"无API密钥"',
    '"No applications"': '"无应用"',
    '"No attachments"': '"无附件"',
    '"No broadcasts"': '"无群发邮件"',
    '"No campaigns"': '"无营销活动"',
    '"No changes"': '"无更改"',
    '"No channels"': '"无渠道"',
    '"No contacts"': '"无联系人"',
    '"No data"': '"无数据"',
    '"No data available"': '"无数据可用"',
    '"No entries"': '"无条目"',
    '"No events"': '"无事件"',
    '"No fields"': '"无字段"',
    '"No file"': '"无文件"',
    '"No files"': '"无文件"',
    '"No filters"': '"无筛选"',
    '"No groups"': '"无分组"',
    '"No history"': '"无历史记录"',
    '"No items"': '"无项目"',
    '"No labels"': '"无标签"',
    '"No links"': '"无链接"',
    '"No logs"': '"无日志"',
    '"No members"': '"无成员"',
    '"No messages"': '"无消息"',
    '"No notifications"': '"无通知"',
    '"No pages"': '"无页面"',
    '"No results"': '"无结果"',
    '"No results found"': '"未找到结果"',
    '"No segments"': '"无细分"',
    '"No senders"': '"无发件人"',
    '"No settings"': '"无设置"',
    '"No subscribers"': '"无订阅者"',
    '"No tags"': '"无标签"',
    '"No templates"': '"无模板"',
    '"No users"': '"无用户"',
    '"No webhooks"': '"无Webhook"',
    '"No workspaces"': '"无工作区"',
    '"None"': '"无"',
    '"Normal"': '"正常"',
    '"Not"': '"不"',
    '"Not applicable"': '"不适用"',
    '"Not available"': '"不可用"',
    '"Not found"': '"未找到"',
    '"Not found (404)"': '"未找到（404）"',
    '"Not implemented"': '"未实现"',
    '"Not installed"': '"未安装"',
    '"Not published"': '"未发布"',
    '"Not registered"': '"未注册"',
    '"Not required"': '"非必填"',
    '"Not running"': '"未运行"',
    '"Not selected"': '"未选择"',
    '"Not set"': '"未设置"',
    '"Not started"': '"未开始"',
    '"Not supported"': '"不支持"',
    '"Not visible"': '"不可见"',
    '"Note"': '"备注"',
    '"Notes"': '"备注"',
    '"Nothing"': '"无"',
    '"Notification"': '"通知"',
    '"Notifications"': '"通知"',
    '"Number"': '"数字"',
    '"Number of contacts"': '"联系人数"',
    '"Number of items"': '"项目数"',
    '"Number of results"': '"结果数"',
    '"Number of rows"': '"行数"',
    '"Number of subscribers"': '"订阅者数"',
    '"Number of users"': '"用户数"',
    '"OAuth2"': '"OAuth2"',
    '"Object"': '"对象"',
    '"Objects"': '"对象"',
    '"Occurrence"': '"发生"',
    '"Occurrences"': '"发生"',
    '"Off"': '"关闭"',
    '"OK"': '"确定"',
    '"On"': '"开启"',
    '"Ongoing"': '"进行中"',
    '"Only"': '"仅"',
    '"Only if"': '"仅当"',
    '"Open"': '"打开"',
    '"Open Rate"': '"打开率"',
    '"Open links in"': '"打开链接于"',
    '"Open source"': '"开源"',
    '"Opened"': '"已打开"',
    '"Operating mode"': '"运行模式"',
    '"Operations"': '"操作"',
    '"Operator"': '"运算符"',
    '"Optional"': '"可选"',
    '"Options"': '"选项"',
    '"Options:"': '"选项："',
    '"Order"': '"排序"',
    '"Order by"': '"排序方式"',
    '"Organization"': '"组织"',
    '"Organization ID"': '"组织ID"',
    '"Organization name"': '"组织名称"',
    '"Organizations"': '"组织"',
    '"Origin"': '"来源"',
    '"Origin URL"': '"来源URL"',
    '"Other"': '"其他"',
    '"Others"': '"其他"',
    '"Outbound webhooks"': '"出站Webhook"',
    '"Output"': '"输出"',
    '"Output field"': '"输出字段"',
    '"Output format"': '"输出格式"',
    '"Outside"': '"外部"',
    '"Overwrite"': '"覆盖"',
    '"Owner"': '"所有者"',
    '"Owner ID"': '"所有者ID"',
    '"Page"': '"页面"',
    '"Page footer"': '"页面底部"',
    '"Page header"': '"页面头部"',
    '"Page not found"': '"页面未找到"',
    '"Page number"': '"页码"',
    '"Page size"': '"页面大小"',
    '"Pages"': '"页面"',
    '"Pagination"': '"分页"',
    '"Palette"': '"调色板"',
    '"Panel"': '"面板"',
    '"Parameter"': '"参数"',
    '"Parameters"': '"参数"',
    '"Parent"': '"父级"',
    '"Parent ID"': '"父级ID"',
    '"Password"': '"密码"',
    '"Password is required"': '"密码为必填"',
    '"Password reset"': '"密码重置"',
    '"Password strength"': '"密码强度"',
    '"Path"': '"路径"',
    '"Path parameters"': '"路径参数"',
    '"Pattern"': '"模式"',
    '"Payload"': '"负载"',
    '"Pending"': '"待处理"',
    '"People"': '"人员"',
    '"Percent"': '"百分比"',
    '"Percentage"': '"百分比"',
    '"Period"': '"期间"',
    '"Permanent"': '"永久"',
    '"Permission"': '"权限"',
    '"Permission denied"': '"权限被拒绝"',
    '"Permission granted"': '"权限已授予"',
    '"Permissions"': '"权限"',
    '"Personal"': '"个人"',
    '"Personal data"': '"个人数据"',
    '"Personal information"': '"个人信息"',
    '"Phone"': '"电话"',
    '"Phone number"': '"电话号码"',
    '"Placeholder"': '"占位符"',
    '"Plan"': '"计划"',
    '"Plans"': '"计划"',
    '"Please"': '"请"',
    '"Please check"': '"请检查"',
    '"Please confirm"': '"请确认"',
    '"Please enter"': '"请输入"',
    '"Please fill in"': '"请填写"',
    '"Please select"': '"请选择"',
    '"Please try again"': '"请重试"',
    '"Please wait"': '"请稍候"',
    '"Plugin"': '"插件"',
    '"Plus"': '"加"',
    '"Point"': '"点"',
    '"Policy"': '"策略"',
    '"Port"': '"端口"',
    '"Position"': '"位置"',
    '"Post"': '"文章"',
    '"Posts"': '"文章"',
    '"Power"': '"电源"',
    '"Precision"': '"精度"',
    '"Prefix"': '"前缀"',
    '"Prepare"': '"准备"',
    '"Prepared"': '"已准备"',
    '"Present"': '"现在"',
    '"Preview"': '"预览"',
    '"Preview text"': '"预览文本"',
    '"Previous"': '"上一步"',
    '"Previous page"': '"上一页"',
    '"Primary"': '"主要"',
    '"Primary color"': '"主色"',
    '"Primary email"': '"主要邮箱"',
    '"Primary key"': '"主键"',
    '"Print"': '"打印"',
    '"Priority"': '"优先级"',
    '"Privacy"': '"隐私"',
    '"Private"': '"私有"',
    '"Process"': '"处理"',
    '"Processing"': '"处理中"',
    '"Processing data"': '"处理数据中"',
    '"Processor"': '"处理器"',
    '"Product"': '"产品"',
    '"Products"': '"产品"',
    '"Profile"': '"配置文件"',
    '"Profile ID"': '"配置文件ID"',
    '"Profiles"': '"配置文件"',
    '"Profit"': '"利润"',
    '"Progress"': '"进度"',
    '"Project"': '"项目"',
    '"Projects"': '"项目"',
    '"Prompt"': '"提示"',
    '"Prompts"': '"提示词"',
    '"Properties"': '"属性"',
    '"Property"': '"属性"',
    '"Provider"': '"提供商"',
    '"Providers"': '"提供商"',
    '"Public"': '"公开"',
    '"Publish"': '"发布"',
    '"Publish date"': '"发布日期"',
    '"Publish now"': '"立即发布"',
    '"Published"': '"已发布"',
    '"Published on"': '"发布于"',
    '"Published posts"': '"已发布的文章"',
    '"Publisher"': '"发布者"',
    '"Pull"': '"拉取"',
    '"Push"': '"推送"',
    '"Put"': '"放置"',
    '"Quality"': '"质量"',
    '"Query"': '"查询"',
    '"Query builder"': '"查询构建器"',
    '"Query parameters"': '"查询参数"',
    '"Query string"': '"查询字符串"',
    '"Queue"': '"队列"',
    '"Queue name"': '"队列名称"',
    '"Queued"': '"已排队"',
    '"Queues"': '"队列"',
    '"Quick"': '"快速"',
    '"Quick actions"': '"快速操作"',
    '"Quick add"': '"快速添加"',
    '"Quick edit"': '"快速编辑"',
    '"Quick view"': '"快速查看"',
    '"Quit"': '"退出"',
    '"Quota"': '"配额"',
    '"RPC"': '"RPC"',
    '"Radius"': '"半径"',
    '"Random"': '"随机"',
    '"Range"': '"范围"',
    '"Rate"': '"速率"',
    '"Rate limit"': '"速率限制"',
    '"Raw"': '"原始"',
    '"Raw data"': '"原始数据"',
    '"Read"': '"读取"',
    '"Read less"': '"收起"',
    '"Read more"': '"阅读更多"',
    '"Read only"': '"只读"',
    '"Read permissions"': '"读取权限"',
    '"Read token"': '"读取令牌"',
    '"Ready"': '"就绪"',
    '"Real"': '"真实"',
    '"Realtime"': '"实时"',
    '"Reason"': '"原因"',
    '"Reasons"': '"原因"',
    '"Rebuild"': '"重建"',
    '"Receive"': '"接收"',
    '"Received"': '"已接收"',
    '"Recent"': '"最近"',
    '"Recent activity"': '"最近活动"',
    '"Recent items"': '"最近项目"',
    '"Recent searches"': '"最近搜索"',
    '"Recipient"': '"收件人"',
    '"Recipient Feed"': '"收件人数据源"',
    '"Recipient data"': '"收件人数据"',
    '"Recipient email"': '"收件人邮箱"',
    '"Recipients"': '"收件人"',
    '"Recipients count"': '"收件人数"',
    '"Recipients data"': '"收件人数据"',
    '"Record"': '"记录"',
    '"Record ID"': '"记录ID"',
    '"Records"': '"记录"',
    '"Recover"': '"恢复"',
    '"Redirect"': '"重定向"',
    '"Redirect URL"': '"重定向URL"',
    '"Redo"': '"重做"',
    '"Refresh"': '"刷新"',
    '"Refersh"': '"刷新"',
    '"Regenerate"': '"重新生成"',
    '"Regenrate"': '"重新生成"',
    '"Region"': '"区域"',
    '"Regional"': '"区域"',
    '"Register"': '"注册"',
    '"Registry"': '"注册表"',
    '"Regular"': '"常规"',
    '"Related"': '"相关"',
    '"Related items"': '"相关项目"',
    '"Reload"': '"重新加载"',
    '"Remaining"': '"剩余"',
    '"Remove"': '"移除"',
    '"Remove all"': '"全部移除"',
    '"Remove field"': '"移除字段"',
    '"Remove item"': '"移除项目"',
    '"Remove label"': '"移除标签"',
    '"Remove member"': '"移除成员"',
    '"Remove permission"': '"移除权限"',
    '"Remove tag"': '"移除标签"',
    '"Removed"': '"已移除"',
    '"Rename"': '"重命名"',
    '"Renamed"': '"已重命名"',
    '"Repair"': '"修复"',
    '"Replace"': '"替换"',
    '"Replace all"': '"替换全部"',
    '"Replace with"': '"替换为"',
    '"Report"': '"报告"',
    '"Report bug"': '"报告错误"',
    '"Reporter"': '"报告者"',
    '"Reports"': '"报告"',
    '"Repository"': '"仓库"',
    '"Request"': '"请求"',
    '"Request body"': '"请求正文"',
    '"Request headers"': '"请求头"',
    '"Request ID"': '"请求ID"',
    '"Request method"': '"请求方法"',
    '"Request timeout"': '"请求超时"',
    '"Request URL"': '"请求URL"',
    '"Requests"': '"请求"',
    '"Required"': '"必填"',
    '"Required field"': '"必填字段"',
    '"Required fields"': '"必填字段"',
    '"Required permissions"': '"必填权限"',
    '"Requirements"': '"要求"',
    '"Research"': '"研究"',
    '"Reset"': '"重置"',
    '"Reset all"': '"全部重置"',
    '"Reset filters"': '"重置筛选"',
    '"Reset password"': '"重置密码"',
    '"Resolve"': '"解决"',
    '"Resolved"': '"已解决"',
    '"Resolve now"': '"立即解决"',
    '"Resource"': '"资源"',
    '"Resources"': '"资源"',
    '"Respond"': '"响应"',
    '"Response"': '"响应"',
    '"Response body"': '"响应正文"',
    '"Response headers"': '"响应头"',
    '"Response status"': '"响应状态"',
    '"Response time"': '"响应时间"',
    '"Response URL"': '"响应URL"',
    '"Responses"': '"响应"',
    '"Rest"': '"其余"',
    '"Restart"': '"重启"',
    '"Restart now"': '"立即重启"',
    '"Restarted"': '"已重启"',
    '"Restore"': '"恢复"',
    '"Restored"': '"已恢复"',
    '"Result"': '"结果"',
    '"Result field"': '"结果字段"',
    '"Results"': '"结果"',
    '"Resubscribe"': '"重新订阅"',
    '"Resumed"': '"已恢复"',
    '"Resume"': '"继续"',
    '"Retarget"': '"重新定位"',
    '"Retention"': '"保留"',
    '"Retry"': '"重试"',
    '"Retry all"': '"全部重试"',
    '"Retry count"': '"重试次数"',
    '"Retry failed"': '"重试失败"',
    '"Retry limit"': '"重试限制"',
    '"Retry timeout"': '"重试超时"',
    '"Return"': '"返回"',
    '"Return to"': '"返回到"',
    '"Revenue"': '"收入"',
    '"Revert"': '"恢复"',
    '"Review"': '"审核"',
    '"Reviewer"': '"审核者"',
    '"Revoke"': '"撤销"',
    '"Revoked"': '"已撤销"',
    '"Rich text"': '"富文本"',
    '"Right"': '"右"',
    '"Right align"': '"右对齐"',
    '"Right margin"': '"右外边距"',
    '"Role"': '"角色"',
    '"Role ID"': '"角色ID"',
    '"Role name"': '"角色名称"',
    '"Roles"': '"角色"',
    '"Rollback"': '"回滚"',
    '"Root"': '"根"',
    '"Root cause"': '"根本原因"',
    '"Root URL"': '"根URL"',
    '"Rotate"': '"旋转"',
    '"Routing"': '"路由"',
    '"Rows"': '"行"',
    '"Rows per page"': '"每页行数"',
    '"Rule"': '"规则"',
    '"Rule ID"': '"规则ID"',
    '"Rule name"': '"规则名称"',
    '"Rules"': '"规则"',
    '"Run"': '"运行"',
    '"Run at"': '"运行于"',
    '"Run now"': '"立即运行"',
    '"Running"': '"运行中"',
    '"Runtime"': '"运行时"',
    '"Safe"': '"安全"',
    '"SAML"': '"SAML"',
    '"Sample"': '"示例"',
    '"Sample data"': '"示例数据"',
    '"Save"': '"保存"',
    '"Save & Continue"': '"保存并继续"',
    '"Save as"': '"另存为"',
    '"Save as draft"': '"保存为草稿"',
    '"Save changes"': '"保存更改"',
    '"Save close"': '"保存并关闭"',
    '"Saved"': '"已保存"',
    '"Saving"': '"保存中"',
    '"Scale"': '"缩放"',
    '"Schedule"': '"排程"',
    '"Scheduled"': '"已排程"',
    '"Scheduled for"': '"排程于"',
    '"Schema"': '"模式"',
    '"Score"': '"分数"',
    '"Screen"': '"屏幕"',
    '"Screenshot"': '"截图"',
    '"Script"': '"脚本"',
    '"Search"': '"搜索"',
    '"Search by"': '"搜索"',
    '"Search contacts"': '"搜索联系人"',
    '"Search query"': '"搜索查询"',
    '"Search results"': '"搜索结果"',
    '"Search results for"': '"搜索结果："',
    '"Search term"': '"搜索词"',
    '"Search users"': '"搜索用户"',
    '"Season"': '"季节"',
    '"Second"': '"秒"',
    '"Secondary"': '"次要"',
    '"Secret"': '"密钥"',
    '"Secret ID"': '"密钥ID"',
    '"Secret key"': '"密钥"',
    '"Secrets"': '"密钥"',
    '"Section"': '"部分"',
    '"Sections"': '"部分"',
    '"Security"': '"安全"',
    '"Segment"': '"细分"',
    '"Segment ID"': '"细分ID"',
    '"Segment name"': '"细分名称"',
    '"Segments"': '"细分"',
    '"Select"': '"选择"',
    '"Selectable"': '"可选"',
    '"Selected"': '"已选择"',
    '"Selected items"': '"已选项目"',
    '"Selected rows"': '"已选行"',
    '"Selections"': '"选择"',
    '"Self"': '"自己"',
    '"Send"': '"发送"',
    '"Send at"': '"发送于"',
    '"Send email"': '"发送邮件"',
    '"Send link"': '"发送链接"',
    '"Send notification"': '"发送通知"',
    '"Send now"': '"立即发送"',
    '"Send on"': '"发送于"',
    '"Send test email"': '"发送测试邮件"',
    '"Send test notification"': '"发送测试通知"',
    '"Sender"': '"发件人"',
    '"Sender ID"': '"发件人ID"',
    '"Sender name"': '"发件人名称"',
    '"Senders"': '"发件人"',
    '"Sending"': '"发送中"',
    '"Sending domain"': '"发送域名"',
    '"Sending emails"': '"发送邮件中"',
    '"Sent"': '"已发送"',
    '"Sent emails"': '"已发送邮件"',
    '"Sent to"': '"已发送至"',
    '"SEO"': '"SEO"',
    '"Sequence"': '"序列"',
    '"Sequences"': '"序列"',
    '"Server"': '"服务器"',
    '"Server error"': '"服务器错误"',
    '"Server URL"': '"服务器URL"',
    '"Servers"': '"服务器"',
    '"Service"': '"服务"',
    '"Service ID"': '"服务ID"',
    '"Service name"': '"服务名称"',
    '"Service unavailable"': '"服务不可用"',
    '"Services"': '"服务"',
    '"Session"': '"会话"',
    '"Session ID"': '"会话ID"',
    '"Sessions"': '"会话"',
    '"Set"': '"设置"',
    '"Set as default"': '"设为默认"',
    '"Set default"': '"设为默认"',
    '"Setting"': '"设置"',
    '"Settings"': '"设置"',
    '"Setup"': '"设置"',
    '"Setup guide"': '"设置指南"',
    '"Severity"': '"严重程度"',
    '"Share"': '"分享"',
    '"Share link"': '"分享链接"',
    '"Shared"': '"已分享"',
    '"Shared with"': '"已分享给"',
    '"Shares"': '"分享"',
    '"Sharing"': '"分享中"',
    '"Short"': '"短"',
    '"Short text"': '"短文本"',
    '"Show"': '"显示"',
    '"Show advanced settings"': '"显示高级设置"',
    '"Show field"': '"显示字段"',
    '"Show hidden"': '"显示隐藏"',
    '"Show less"': '"收起"',
    '"Show more"': '"展开"',
    '"Shown"': '"已显示"',
    '"Shows"': '"显示"',
    '"Showing"': '"显示中"',
    '"Sign"': '"符号"',
    '"Sign in"': '"登录"',
    '"Sign out"': '"登出"',
    '"Similar posts"': '"相关文章"',
    '"Simple"': '"简单"',
    '"Simple text"': '"简单文本"',
    '"Since"': '"自"',
    '"Single"': '"单个"',
    '"Single column"': '"单列"',
    '"Single line"': '"单行"',
    '"Size"': '"大小"',
    '"Size (px)"': '"大小（像素）"',
    '"Skeleton"': '"骨架"',
    '"Skip"': '"跳过"',
    '"Skipped"': '"已跳过"',
    '"Slack"': '"Slack"',
    '"Slides"': '"幻灯片"',
    '"Slow"': '"慢"',
    '"Small"': '"小"',
    '"Smart"': '"智能"',
    '"SMTP"': '"SMTP"',
    '"Snippet"': '"代码片段"',
    '"Social"': '"社交"',
    '"Social media"': '"社交媒体"',
    '"Solution"': '"解决方案"',
    '"Sort"': '"排序"',
    '"Sortable"': '"可排序"',
    '"Sorted"': '"已排序"',
    '"Source"': '"来源"',
    '"Source code"': '"源代码"',
    '"Source URL"': '"源URL"',
    '"Sources"': '"来源"',
    '"Span"': '"跨"',
    '"Special"': '"特殊"',
    '"Specific value"': '"特定值"',
    '"Specify"': '"指定"',
    '"Split"': '"拆分"',
    '"Split test"': '"拆分测试"',
    '"SQL"': '"SQL"',
    '"SQL query"': '"SQL查询"',
    '"SSO"': '"SSO"',
    '"Stack"': '"堆叠"',
    '"Stage"': '"阶段"',
    '"Stages"': '"阶段"',
    '"Standard"': '"标准"',
    '"Start"': '"开始"',
    '"Start at"': '"开始于"',
    '"Start date"': '"开始日期"',
    '"Start node"': '"起始节点"',
    '"Start now"': '"立即开始"',
    '"Start page"': '"起始页面"',
    '"Start time"': '"开始时间"',
    '"Started"': '"已开始"',
    '"Starting"': '"开始中"',
    '"State"': '"状态"',
    '"Statement"': '"语句"',
    '"Static"': '"静态"',
    '"Statistics"': '"统计"',
    '"Stats"': '"统计"',
    '"Status"': '"状态"',
    '"Status code"': '"状态码"',
    '"Status message"': '"状态消息"',
    '"Status page"': '"状态页面"',
    '"Step"': '"步骤"',
    '"Steps"': '"步骤"',
    '"Stock"': '"库存"',
    '"Stop"': '"停止"',
    '"Stop now"': '"立即停止"',
    '"Stopped"': '"已停止"',
    '"Storage"': '"存储"',
    '"Storage bucket"': '"存储桶"',
    '"Storage region"': '"存储区域"',
    '"Store"': '"存储"',
    '"Stored"': '"已存储"',
    '"Strategy"': '"策略"',
    '"Strength"': '"强度"',
    '"Strict"': '"严格"',
    '"String"': '"字符串"',
    '"Strings"': '"字符串"',
    '"Stroke"': '"描边"',
    '"Structure"': '"结构"',
    '"Style"': '"样式"',
    '"Styles"': '"样式"',
    '"Subject"': '"主题"',
    '"Submit"': '"提交"',
    '"Submitted"': '"已提交"',
    '"Subscribers"': '"订阅者"',
    '"Subscription"': '"订阅"',
    '"Subscription status"': '"订阅状态"',
    '"Subscriptions"': '"订阅"',
    '"Success"': '"成功"',
    '"Success rate"': '"成功率"',
    '"Successfully"': '"成功"',
    '"Summary"': '"摘要"',
    '"Support"': '"支持"',
    '"Supported"': '"支持"',
    '"Supports"': '"支持"',
    '"Switch"': '"切换"',
    '"Switch to"': '"切换到"',
    '"Switched"': '"已切换"',
    '"Symbol"': '"符号"',
    '"Sync"': '"同步"',
    '"Synced"': '"已同步"',
    '"Syncing"': '"同步中"',
    '"Syntax"': '"语法"',
    '"System"': '"系统"',
    '"System error"': '"系统错误"',
    '"Table"': '"表格"',
    '"Tab"': '"标签"',
    '"Table view"': '"表格视图"',
    '"Tables"': '"表格"',
    '"Tag"': '"标签"',
    '"Tags"': '"标签"',
    '"Target"': '"目标"',
    '"Target audience"': '"目标受众"',
    '"Target URL"': '"目标URL"',
    '"Task"': '"任务"',
    '"Tasks"': '"任务"',
    '"Template"': '"模板"',
    '"Template content"': '"模板内容"',
    '"Template ID"': '"模板ID"',
    '"Template name"': '"模板名称"',
    '"Templates"': '"模板"',
    '"Temporary"': '"临时"',
    '"Terms"': '"条款"',
    '"Terms of service"': '"服务条款"',
    '"Test"': '"测试"',
    '"Test connection"': '"测试连接"',
    '"Test data"': '"测试数据"',
    '"Test email"': '"测试邮件"',
    '"Test notification"': '"测试通知"',
    '"Test webhook"': '"测试Webhook"',
    '"Tested"': '"已测试"',
    '"Testing"': '"测试中"',
    '"Text"': '"文本"',
    '"Text alignment"': '"文本对齐"',
    '"Text color"': '"文本颜色"',
    '"Text decoration"': '"文本装饰"',
    '"Text direction"': '"文本方向"',
    '"Text transform"': '"文本转换"',
    '"Text value"': '"文本值"',
    '"Texts"': '"文本"',
    '"Thank you"': '"谢谢"',
    '"Theme"': '"主题"',
    '"Themes"': '"主题"',
    '"Then"': '"然后"',
    '"There are no"': '"没有"',
    '"This"': '"这"',
    '"This action cannot be undone"': '"此操作无法撤销"',
    '"This field"': '"此字段"',
    '"This month"': '"本月"',
    '"This page"': '"此页面"',
    '"This week"': '"本周"',
    '"This year"': '"今年"',
    '"Those"': '"那些"',
    '"Thread"': '"线程"',
    '"Threads"': '"线程"',
    '"Through"': '"通过"',
    '"Throughout"': '"遍及"',
    '"Thumbnail"': '"缩略图"',
    '"Thumbnails"': '"缩略图"',
    '"Time"': '"时间"',
    '"Time out"': '"超时"',
    '"Time range"': '"时间范围"',
    '"Time zone"': '"时区"',
    '"Timeline"': '"时间线"',
    '"Times"': '"次数"',
    '"Timezone"': '"时区"',
    '"Title"': '"标题"',
    '"Titles"': '"标题"',
    '"Toast"': '"提示"',
    '"Today"': '"今天"',
    '"Toggle"': '"切换"',
    '"Toggle all"': '"切换全部"',
    '"Token"': '"令牌"',
    '"Tokens"': '"令牌"',
    '"Tomorrow"': '"明天"',
    '"Too many"': '"太多"',
    '"Tool"': '"工具"',
    '"Toolbar"': '"工具栏"',
    '"Tools"': '"工具"',
    '"Top"': '"顶部"',
    '"Topic"': '"主题"',
    '"Topics"': '"主题"',
    '"Total"': '"总计"',
    '"Total contacts"': '"联系人总计"',
    '"Total records"': '"记录总计"',
    '"Total results"': '"结果总计"',
    '"Total rows"': '"总行数"',
    '"Total sent"': '"已发送总计"',
    '"Total users"': '"用户总计"',
    '"Trace"': '"追踪"',
    '"Tracking"': '"追踪"',
    '"Traffic"': '"流量"',
    '"Transfer"': '"转移"',
    '"Transferred"': '"已转移"',
    '"Transform"': '"转换"',
    '"Transformed"': '"已转换"',
    '"Transition"': '"过渡"',
    '"Translate"': '"翻译"',
    '"Translated"': '"已翻译"',
    '"Translation"': '"翻译"',
    '"Translations"': '"翻译"',
    '"Transparent"': '"透明"',
    '"Transport"': '"传输"',
    '"Trap"': '"陷阱"',
    '"Trash"': '"垃圾箱"',
    '"Trend"': '"趋势"',
    '"Trends"': '"趋势"',
    '"Trial"': '"试用"',
    '"Trigger"': '"触发器"',
    '"Triggered"': '"已触发"',
    '"Triggers"': '"触发器"',
    '"True"': '"真"',
    '"Turn off"': '"关闭"',
    '"Turn on"': '"开启"',
    '"Tutorial"': '"教程"',
    '"Type"': '"类型"',
    '"Types"': '"类型"',
    '"Typical"': '"典型"',
    '"UID"': '"UID"',
    '"Unable"': '"无法"',
    '"Unauthorized"': '"未授权"',
    '"Unauthorized access"': '"未授权访问"',
    '"Unavailable"': '"不可用"',
    '"Unchanged"': '"未更改"',
    '"Unconfirmed"': '"未确认"',
    '"Underline"': '"下划线"',
    '"Undo"': '"撤销"',
    '"Unequal"': '"不等"',
    '"Unexpected"': '"意外"',
    '"Unfavorite"': '"取消收藏"',
    '"Unfollowed"': '"已取消关注"',
    '"Unfriend"': '"取消好友"',
    '"Ungroup"': '"取消分组"',
    '"Unique"': '"唯一"',
    '"Unique ID"': '"唯一ID"',
    '"Unit"': '"单位"',
    '"Unknown"': '"未知"',
    '"Unknown error"': '"未知错误"',
    '"Unless"': '"除非"',
    '"Unlike"': '"不像"',
    '"Unlock"': '"解锁"',
    '"Unlocked"': '"已解锁"',
    '"Unmodified"': '"未修改"',
    '"Unordered"': '"无序"',
    '"Unpause"': '"取消暂停"',
    '"Unpaused"': '"已取消暂停"',
    '"Unprocessed"': '"未处理"',
    '"Unpublished"': '"未发布"',
    '"Unread"': '"未读"',
    '"Unrecognized"': '"无法识别"',
    '"Unsaved"': '"未保存"',
    '"Unsubscribe"': '"退订"',
    '"Unsubscribed"': '"已退订"',
    '"Unsupported"': '"不支持"',
    '"Untitled"': '"无标题"',
    '"Unused"': '"未使用"',
    '"Unverified"': '"未验证"',
    '"Unwanted"': '"不需要"',
    '"Unzip"': '"解压"',
    '"Up"': '"上"',
    '"Up to"': '"高达"',
    '"Up-to-date"': '"最新"',
    '"Update"': '"更新"',
    '"Update available"': '"有可用更新"',
    '"Update now"': '"立即更新"',
    '"Updated"': '"已更新"',
    '"Updated at"': '"更新于"',
    '"Updated by"': '"更新者"',
    '"Updates"': '"更新"',
    '"Updating"': '"更新中"',
    '"Upgrade"': '"升级"',
    '"Upgraded"': '"已升级"',
    '"Upgrading"': '"升级中"',
    '"Upload"': '"上传"',
    '"Upload CSV"': '"上传CSV"',
    '"Upload failed"': '"上传失败"',
    '"Upload file"': '"上传文件"',
    '"Uploaded"': '"已上传"',
    '"Uploaded files"': '"已上传文件"',
    '"Uploading"': '"上传中"',
    '"URL"': '"URL"',
    '"URL encoded"': '"URL编码"',
    '"URL path"': '"URL路径"',
    '"Usage"': '"使用量"',
    '"Usage limits"': '"使用限制"',
    '"Use"': '"使用"',
    '"Use custom endpoint"': '"使用自定义端点"',
    '"Use default"': '"使用默认"',
    '"Use SSL"': '"使用SSL"',
    '"Useful"': '"有用"',
    '"User"': '"用户"',
    '"User guide"': '"用户指南"',
    '"User ID"': '"用户ID"',
    '"User interface"': '"用户界面"',
    '"User name"': '"用户名"',
    '"User not found"': '"用户未找到"',
    '"User profile"': '"用户配置文件"',
    '"User settings"': '"用户设置"',
    '"Users"': '"用户"',
    '"Valid"': '"有效"',
    '"Validate"': '"验证"',
    '"Validated"': '"已验证"',
    '"Validation"': '"验证"',
    '"Validation error"': '"验证错误"',
    '"Value"': '"值"',
    '"Value of"': '"值"',
    '"Values"': '"值"',
    '"Variable"': '"变量"',
    '"Variable name"': '"变量名"',
    '"Variables"': '"变量"',
    '"Variant"': '"变体"',
    '"Variants"': '"变体"',
    '"Version"': '"版本"',
    '"Version control"': '"版本控制"',
    '"Versions"': '"版本"',
    '"Vertical"': '"垂直"',
    '"Vertical align"': '"垂直对齐"',
    '"Via"': '"通过"',
    '"Video"': '"视频"',
    '"View"': '"查看"',
    '"View all"': '"查看全部"',
    '"View details"': '"查看详情"',
    '"View more"': '"查看更多"',
    '"View on GitHub"': '"在GitHub上查看"',
    '"View report"': '"查看报告"',
    '"Views"': '"视图"',
    '"Visibility"': '"可见性"',
    '"Visit"': '"访问"',
    '"Visit website"': '"访问网站"',
    '"Visits"': '"访问"',
    '"Volume"': '"音量"',
    '"Vote"': '"投票"',
    '"Warning"': '"警告"',
    '"Warnings"': '"警告"',
    '"Watch"': '"观看"',
    '"Webhook"': '"Webhook"',
    '"Webhook events"': '"Webhook事件"',
    '"Webhook URL"': '"Webhook URL"',
    '"Webhooks"': '"Webhook"',
    '"Website"': '"网站"',
    '"Website URL"': '"网站URL"',
    '"Week"': '"周"',
    '"Weekly"': '"每周"',
    '"Weight"': '"权重"',
    '"Welcome"': '"欢迎"',
    '"What"': '"什么"',
    '"When"': '"当"',
    '"Where"': '"在哪里"',
    '"Which"': '"哪个"',
    '"While"': '"当"',
    '"Who"': '"谁"',
    '"Width"': '"宽度"',
    '"Width (px)"': '"宽度（像素）"',
    '"Width in pixels"': '"宽度（像素）"',
    '"Wildcard"': '"通配符"',
    '"Window"': '"窗口"',
    '"Wizard"': '"向导"',
    '"Word"': '"单词"',
    '"Words"': '"单词"',
    '"Workflow"': '"工作流"',
    '"Workflows"': '"工作流"',
    '"Working"': '"工作中"',
    '"Workspace"': '"工作区"',
    '"Workspace ID"': '"工作区ID"',
    '"Workspace name"': '"工作区名称"',
    '"Workspaces"': '"工作区"',
    '"Wrap"': '"换行"',
    '"Wrapper"': '"包装"',
    '"Write"': '"写入"',
    '"Write permissions"': '"写入权限"',
    '"Write token"': '"写入令牌"',
    '"Writer"': '"写入者"',
    '"XML"': '"XML"',
    '"Year"': '"年"',
    '"Years"': '"年"',
    '"Yes"': '"是"',
    '"Yes, cancel"': '"是，取消"',
    '"Yes, continue"': '"是，继续"',
    '"Yes, delete"': '"是，删除"',
    '"Yesterday"': '"昨天"',
    '"You"': '"您"',
    '"Your"': '"您的"',
    '"Your email"': '"您的邮箱"',
    '"Your name"': '"您的名称"',
    '"Your workspace"': '"您的工作区"',
    '"Your workspace API key"': '"您的工作区API密钥"',
    '"Zero"': '"零"',
    '"Zone"': '"区域"',
    '"Zoom"': '"缩放"',
    '"Zoom in"': '"放大"',
    '"Zoom out"': '"缩小"',
    '"emails per day"': '"每天邮件数"',
    '"emails per hour"': '"每小时邮件数"',
    '"exactly"': '"精确"',
}

def has_chinese(text):
    return any('\u4e00' <= c <= '\u9fff' for c in text)

def main():
    with open(zh_po, 'r', encoding='utf-8') as f:
        content = f.read()

    lines = content.split('\n')
    translated_count = 0
    total_entries = 0

    for key, value in TRANSLATIONS.items():
        key_str = key[1:-1]  # Remove quotes
        value_str = value[1:-1]
        escaped_key = key_str.replace('\\"', '"')
        escaped_value = value_str.replace('\\"', '"')

        if escaped_key in content:
            total_entries += 1
            original = f'msgstr "{key_str}"'
            replacement = f'msgstr "{value_str}"'
            if original in content:
                content = content.replace(original, replacement)
                translated_count += 1

    with open(zh_po, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Entries found needing translation: {total_entries}")
    print(f"Translated in this batch: {translated_count}")

if __name__ == '__main__':
    main()
